name: Sketch In Studios
favicon: null
layout_spectrum: 0.99911
typography_spectrum: 0.05117
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bd1f2d'
    - '#ce4e58'
    - '#e69ea4'
    - '#ffffff'
    - '#ff0000'
  brandStrength: 0.0625
  lightness: 0.8125
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
